### ISSUE TITLE
Needs Manifest V2 and cf-deployment support

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry-incubator/cephfs-bosh-release#3]
Manifest v2 and cf-deployment can modify deployment menifest using 'operation' files without modifing release itself.
I think this is better then bosh runtime-config because cephdriver only needs on diego-cell.
How about consider this to discribe on README.md?

**Comment by kukgini** [comment]
Please refer to this code as operation file:

```
- type: replace
  path: /releases/-
  value:
    name: cephfs
    version: "0+dev.1"

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: cephdriver
    release: cephfs
    properties: {}

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/volume_services_enabled?
  value: true

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/volume_services_enabled?
  value: true

- type: replace
  path: /instance_groups/name=cc-clock/jobs/name=cloud_controller_clock/properties/cc/volume_services_enabled?
  value: true
```
